name: build_nodejs

on:
  push:
    branches:
      - main #ветка для пуша
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' #версия ноды

      - name: install_dependencies
        run: npm install #установка пакетов
      
      - name: build
        run: npm run build #команда сборки
      
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist  #команда сохранения в созданую директорию
      - run: zip -r dist.zip dist/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist.zip"
